# Generated by Django 4.2.7 on 2025-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('manifesto', models.FileField(blank=True, upload_to='manifestos/')),
                ('photo', models.ImageField(blank=True, upload_to='candidates/')),
                ('manifesto_text', models.TextField(blank=True)),
            ],
        ),
    ]
