# Generated by Django 4.2.7 on 2025-12-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_executive_phone_number_executive_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='photo_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image for database storage'),
        ),
    ]
