# Generated by Django 4.2.7 on 2025-12-11 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('passport_photo', models.ImageField(blank=True, upload_to='members/passport/')),
                ('membership_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='members/qrcodes/')),
                ('id_card_generated_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
